### ISSUE TITLE
Keep CHANGELOG.txt up to date with each new release and add version numbers to it too.

### ISSUE THREAD

**Issue by klonos** [Thiht/markdown-viewer#34]
CHANGELOG.txt has not been updated since November 2013 and its entries do not include version numbers.

Could there be a way to automate this like for example have it be auto-generated from the commit log? If not, can you then update your release procedure to include a step to update the file before release?

Also, it would be great to keep [AMO.org release page](https://addons.mozilla.org/firefox/addon/markdown-viewer/versions/) up to date too since that's where most people download the addon from..

**Comment by Thiht** [comment]
I was thinking about dropping the CHANGELOG, for a tiny project like that I think the Git log itself does a pretty good job. And from now on I'll try to add Git tags for the future releases.

About the AMO release page, it's updated automatically whenever I submit a new version. The last version is 1.8, I think it's everything the users need to know since they'll propably install the latest one.

**Comment by Thiht** [comment]
Removed the CHANGELOG
