### ISSUE TITLE
Empty table cells not rendered after bracketed text

### ISSUE THREAD

**Issue by PanderMusubi** [Thiht/markdown-viewer#44]
A table such as:

| aaaaa  | eeeeeeeeeeeeeee                | ccccccccccccccc |
| ------ | ------------------------------ | --------------- |
| dddddd | eeeeeeeee                      | [ff]            |
| dddddd | eeeeeeeeeeeeeee                |                 |
| dddddd | eeeeeeeeee                     |                 |

does not render properly in Firefox. The empty cells under [ff] (text with brackets, not a link) are not rendered. There is no horizontel line separating them. See attachment.
![tabele-bug](https://cloud.githubusercontent.com/assets/198964/9698393/bd95062c-53b3-11e5-88e4-8f27281a18eb.png)

**Comment by PanderMusubi** [comment]
Note that the `W.` in the screenshot represents the `ff` of the example.

**Comment by Thiht** [comment]
Should be fixed since markdown-it

**Comment by klonos** [comment]
...confirming fixed in 1.10 (filed a separate issue for the errors at the top of the page: #64):

![markdown_viewer-issue44_fixed](https://cloud.githubusercontent.com/assets/2423362/13313154/f1233f6c-dbef-11e5-9350-953c30b3f64f.png)

Just a question though... I've noticed that if the table starts at the very first line of the file, it is rendered as plain text:

![markdown_viewer-issue44_fixed-but_table_needs_to_start_after_first_line](https://cloud.githubusercontent.com/assets/2423362/13313231/7657c810-dbf0-11e5-8795-a2eb5f72fe8d.png)

Separate issue? Related to #64 perhaps?
