### ISSUE TITLE
Support colspan and rowspan to join table cells

### ISSUE THREAD

**Issue by PanderMusubi** [Thiht/markdown-viewer#45]
Please, support colspan and rowspan to join table cells.

See also http://etherealmind.com/who-am-i/markdown-reference/ and http://talk.commonmark.org/t/tables-in-pure-markdown/81/47 and search for "span".

**Comment by Thiht** [comment]
That's a [markdown-it](https://github.com/markdown-it/markdown-it) issue, so I can't really do anything about it. Moreover, this feature of Markdown doesn't seem to be completely standardized yet

**Comment by PanderMusubi** [comment]
Could you please raise that as an issue there? Thanks

**Comment by Thiht** [comment]
No sorry, markdown-it follows the CommonMark standard + has a Github Flavour plugin, I'm pretty sure the dev won't accept this as long as it's not standardized nor a really common syntax.

But since markdown-it supports HTML, you can use rowspan and colspan as such:

```html
<table>
  <tr>
    <td>Example</td>
    <td>Of</td>
  </tr>
  <tr>
    <td colspan="2">Colspan</td>
  </tr>
</table>
```

```html
<table>
  <tr>
    <td>Example</td>
    <td rowspan="2">Colspan</td>
  </tr>
  <tr>
    <td>Of</td>
  </tr>
</table>
```

Results in:

![rowspan and colspan with Markdown Viewer](http://i.imgur.com/avAIoY1.png)

with Markdown Viewer.

- - -

More info on rowspan and colspan: 
* http://www.w3schools.com/tags/att_td_rowspan.asp
* http://www.w3schools.com/tags/att_td_colspan.asp

**Comment by PanderMusubi** [comment]
Thanks for the elaboration and examples.
