### ISSUE TITLE
Cannot install because of incompatible firefox version

### ISSUE THREAD

**Issue by urbanhop** [Thiht/markdown-viewer#47]
I changed install rdf to

<Description>
				<em:id>{ec8030f7-c20a-464f-9b0e-13a3a9e97384}</em:id>
				<em:minVersion>4.0</em:minVersion>
				<em:maxVersion>66.0</em:maxVersion>
			</Description>

but firefox still does not allow me to install my local build, complaining "is not compatible". Could you give me a hint please?

Thank you

**Comment by Thiht** [comment]
I close this issue for now since it's a bit old.

If you still have this problem feel free to bump the issue with more information (FF version, OS + version, content of the browser console (`Ctrl+Shift+J`, not `F12`), complete error message or screenshot) and I'll reopen it and try to look into it quickly!

**Comment by urbanhop** [comment]
ok with closing
